# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

try:
    from . import gpufabric_pb2 as gpufabric__pb2
except ImportError:
    import gpufabric_pb2 as gpufabric__pb2

GRPC_GENERATED_VERSION = "1.84.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in gpufabric_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class GPUFabricServiceStub:
    """GPU Fabric gRPC Service definition"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
            "/gpufabric.GPUFabricService/GetHealth",
            request_serializer=gpufabric__pb2.HealthRequest.SerializeToString,
            response_deserializer=gpufabric__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.GetGPUInfo = channel.unary_unary(
            "/gpufabric.GPUFabricService/GetGPUInfo",
            request_serializer=gpufabric__pb2.GPUInfoRequest.SerializeToString,
            response_deserializer=gpufabric__pb2.GPUInfoResponse.FromString,
            _registered_method=True,
        )
        self.GetGPUStatus = channel.unary_unary(
            "/gpufabric.GPUFabricService/GetGPUStatus",
            request_serializer=gpufabric__pb2.GPUStatusRequest.SerializeToString,
            response_deserializer=gpufabric__pb2.GPUStatusResponse.FromString,
            _registered_method=True,
        )
        self.Execute = channel.unary_unary(
            "/gpufabric.GPUFabricService/Execute",
            request_serializer=gpufabric__pb2.ExecuteRequest.SerializeToString,
            response_deserializer=gpufabric__pb2.ExecuteResponse.FromString,
            _registered_method=True,
        )


class GPUFabricServiceServicer:
    """GPU Fabric gRPC Service definition"""

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetGPUInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetGPUStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GPUFabricServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetHealth": grpc.unary_unary_rpc_method_handler(
            servicer.GetHealth,
            request_deserializer=gpufabric__pb2.HealthRequest.FromString,
            response_serializer=gpufabric__pb2.HealthResponse.SerializeToString,
        ),
        "GetGPUInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetGPUInfo,
            request_deserializer=gpufabric__pb2.GPUInfoRequest.FromString,
            response_serializer=gpufabric__pb2.GPUInfoResponse.SerializeToString,
        ),
        "GetGPUStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetGPUStatus,
            request_deserializer=gpufabric__pb2.GPUStatusRequest.FromString,
            response_serializer=gpufabric__pb2.GPUStatusResponse.SerializeToString,
        ),
        "Execute": grpc.unary_unary_rpc_method_handler(
            servicer.Execute,
            request_deserializer=gpufabric__pb2.ExecuteRequest.FromString,
            response_serializer=gpufabric__pb2.ExecuteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "gpufabric.GPUFabricService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("gpufabric.GPUFabricService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class GPUFabricService:
    """GPU Fabric gRPC Service definition"""

    @staticmethod
    def GetHealth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpufabric.GPUFabricService/GetHealth",
            gpufabric__pb2.HealthRequest.SerializeToString,
            gpufabric__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetGPUInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpufabric.GPUFabricService/GetGPUInfo",
            gpufabric__pb2.GPUInfoRequest.SerializeToString,
            gpufabric__pb2.GPUInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetGPUStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpufabric.GPUFabricService/GetGPUStatus",
            gpufabric__pb2.GPUStatusRequest.SerializeToString,
            gpufabric__pb2.GPUStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Execute(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpufabric.GPUFabricService/Execute",
            gpufabric__pb2.ExecuteRequest.SerializeToString,
            gpufabric__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
